name: covid19
dependencies:
 - python=3.7
 - numpy=1.17.4
 - pandas=1.1.3
 - jupyter==1.0.0
 - matplotlib=3.2
 - seaborn=0.11.0
 - cvxopt=1.2.0
 - scikit-learn=0.23
 - statsmodels
 - pip:
   - pmdarima==1.5.2
   - requests==2.25.0
   - statsmodels==0.12.1
